vuejs/vuex

docs/zh-cn/mutations.md

```
vuex.dispatch('INCREMENT', 10) -> store.dispatch('INCREMENT', 10)
```

fix wrong charactor in chinese doc

---

docs/en/concepts.md

Quick pr to add a missing word in `concepts.md`

Add missing word to concepts.md

---

docs/en/actions.md

fix naming consistency in documentation example

---

docs/en/testing.md

I reused the testAction for all my action tests, so I made it a little more reusable for different situations, so I can pass in mocked arguments into the action as an array, and also check for more than one item in the payload. Lastly, I added a check at the end to handle scenarios where an action is called that leads to no mutations being dispatched.

args in testAction, payload as array, check for no dispatches

---

docs/en/getters.md

Add missing backticks at the end of the getters documentation.

Close markdown code block

---

docs/en/concepts.md

A suggestion. Just to make it "synchronized" to the remaining of the guide, where we learn "mutations" before "actions".

concepts.md store - "mutations" before "actions"

---

docs/en/getters.md

Prepended a basic example before getting a bit more advanced...

getters.md - basic example

---

docs/en/getting-started.md

It wasn't immediately apparent to me when going along with the docs that the Vuex instance should be the object exported from the store. After looking at the examples and reading on in the docs it looks like this is the usual intent. Might make sense to add that to the Getting Started page?

Update store with default export to match later docs and examples

---

docs/zh-cn/actions.md

在 http://forum.vuejs.org/topic/3546 中提到了一些翻译中遇到的问题，望得到解答。

zh-cn-docs-patch

---

docs/zh-cn/state.md

屏幕不够宽，对照翻译的时候文字折行了，误删了一行重要的示例代码。—— 《论几个屏幕才够用》

add one important missing line

---

package.json
src/override.js
test/unit/test.js

Proposal on how to fix #121. Feedback appreciated.

Better user error.

---

docs/en/api.md
docs/en/mutations.md
src/index.js
test/unit/test.js

- Added support for 'quiet' flag to middlewares
- Fixed FSB standards https://github.com/acdlite/flux-standard-action
- Updated tests
- Updated docs
- Updated API doc to include 'object style mutation'
Note: Modifies FSB support which could mean breaking changes for users.

[Feature] middlewares to ignore 'silent' mutation && FSB support to standards

---

src/override.js
test/unit/test.js

Someday when I was refactoring my code, I changed some getters name. All things crash with unknown errors. After I digg into the code, and find the reason, I made this PR for you.

console.warn when getter is not a function

---

docs/en/forms.md

Using a computed property in the component will make the state as traceable.

Practicable usage of vuex in form input binding

---

docs/zh-cn/forms.md

在组件中使用计算属性可以使得状态继续保持可跟踪，同时又可方便地使用 v-model 的其他特性。

在表单绑定中使用 vuex 的另一个可行方案

---

docs/en/tutorial.md

The rest of the page used Increment.vue, but this one line uses IncrementButton.vue when referring to the same file

Changing example filename in tutorial doc

---

package.json

In `npm install`, I got below error.
So I update ` babel-runtime`. And fixed error.
```
~/W/vuex git:master ❯❯❯ npm install                                               ◼
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package babel-runtime@5.8.38 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vue-loader@8.5.2 wants babel-runtime@^6.0.0
```

Update babel-runtime version

---

src/index.js
src/util.js
test/unit/test.js

This PR fixes #185, allows to define nested modules like the following code.
Properties does not belongs to `state` or `mutations` key are treated as nested modules.
```js
modules: {
nested: {
moduleA: {
state: {...},
mutations: {...}
},
moduleB: {
state: {...},
mutations: {...}
}
},
moduleC: {
state: {...},
mutations: {...}
}
}
})
console.log(store.state.nested.moduleA)
console.log(store.state.nested.moduleB)
console.log(store.state.moduleC)
```

Allow nested modules

---

logger.d.ts
package.json
types/index.d.ts
types/test/index.ts
types/test/tsconfig.json
types/tsconfig.json
types/vue.d.ts

I had send PR to `typings/registry` to register types of Vuex, but it's not accepted and some advices are given. (https://github.com/typings/registry/pull/599)
I rewrote the type files in external module definition format and divide to three files.
We can publish the types via npm without register typings by this modification.
- `/types/index.d.ts` is the types of Vuex
- `/logger.d.ts` is the types of logger module (`'vuex/logger'`)
- It must be put alongside the actual JS file to enable to import by writing `import createLogger from 'vuex/logger'`.
- `/types/vue.d.ts` is the type extensions for Vue.js (Component options and instance property for Vuex)

Modify type files to external module definition format to publish them via npm

---

src/index.js
test/unit/test.js

This patch fixes #248 
The initialization code of internal VM is moved into `initStoreVM` function (renamed from `initStoreState`).
And `initStoreVM` is called on the end of `module` method to register new getters to internal VM.

Allow to register module getters dynamically

---

circle.yml
src/helpers.js
test/unit/test.js

Added support for `mapState(['a', 'b', 'c'])` syntax.

support array syntax for mapState

---

src/index.js
test/unit/test.js

Fix #277 
This patch moves silent flag of commit method to 3rd argument (2nd argument if object style commit).
```js
store.commit('increment', { amount: 1 }, { silent: true })
// Object style
store.commit({
type: 'increment',
amount: 1
}, { silent: true })
```

[2.0] Move silent flag out of payload

---

src/index.js
test/unit/test.js

This patch fixes #279.
The watchers for store state are destroyed by `registerModule` because of the reset of the store VM.
This patch adds a new VM `_watcherVM`. It just watches store state and does not be destroyed by `registerModule`.

Avoid destroy watch callback even if resetting inner vm

---

src/index.js
test/unit/test.js

This PR fixes #312 
`hotUpdate` did not guard a new module and threw an unexpected error. `Cannot set property 'moduleName' of undefined`
I have fixed to avoid this error and provide warning to indicate needing manual reload.

Provide warning when trying to add a new module on hot reload

---

package.json
src/plugins/logger.js
src/util.js
test/unit/util.js

Fix #326 
The logger plugin throws error if state has circular structure because `JSON.stringify()` cannot handle it.
I added `deepCopy` that handle circular structure and use it in the logger plugin.
I will also open a PR to `next` if this patch is ok.

Support circular structure for logger

---

README.md

Adds an example that explains how to use Vuex in the context of building a realtime app with Feathers.js on the backend.

Adds an additional example

---

src/index.js
src/plugins/logger.js
src/util.js
test/unit/jasmine.json
test/unit/util.js

Same as #327 but for `next` branch.
I also move utility functions in `index.js` to `util.js`.

[2.0] Support circular structure for logger

---

docs/en/api.md

as per `v2.0.0-rc.3`, getters receive 3 arguments: `state, getters, rootState`. However only the first is currently documented. This PR fixes this.

Fix: arguments for getters missing in API

---

docs/en/actions.md

Little nitpick, the variable in the description doesn't match the variable in the example. Alternatively, everything could be renamed to `ctx`.

Docs: Match context explanation with code example

---

docs/en/modules.md

The current namespace description is vague as pointed out on #335.
I've added that "namespace" means adding prefix or suffix to names of getters, actions or mutations, and added an example code of it.

[doc] Add more concrete description for namespace

---

docs/en/getters.md
docs/en/modules.md
docs/en/testing.md

I've added the description of 2nd and 3rd argument of getters since it looks like there are no description for them except for API reference.
And added the example of getters testing. This is the request from #324.

[doc] Add more descriptions of getters

---

docs/en/api.md
docs/en/state.md

I've added `mapState`, `mapGetters`, `mapActions` and `mapMutations` to API reference.
And also update `mapState` description in state.md.

[docs] Add helpers reference and update mapState description

---

examples/shopping-cart/store/actions.js
examples/shopping-cart/store/getters.js
examples/shopping-cart/store/modules/cart.js
examples/shopping-cart/store/modules/products.js

As being pointed out on #370, actions and getters in shopping cart example does not belong to each module. It could mislead the v2.0's module approach.
I've move module specific getters and actions into each module, but keep the ones depend on both module on root.

[example] Move module specific getters and actions into each module

---

docs/en/actions.md
docs/en/api.md

Fix #417 
The description of dispatch method seems to be incorrect against actual behavior.

[Docs] Fix description of dispatch

---

dist/vuex.js
src/index.js
test/unit/test.js

When I declare a `state` key in getters as follow, there is an error:
```js
state: {
count: 0
},
getters: {
state: state => state.count > 0 ? 'hasAny' : 'none'
}
})
```
> Uncaught RangeError: Maximum call stack size exceeded(…)
Check out the simple [demo](https://jsfiddle.net/xiaoyanhao/4wxktgx1/) and the error will be logged in the console.
Finally I found there will be a **circular** call if declaring `state` key in getters:
1. `Getters` is treated as computed properties and `state` as data properties (under a `state` key) in `Vuex.Store._vm`. However, in vue, if there is a same key both in `computed` and `data`, we will always get the computed property using proxied properties of the vue instance.
```js
let vm = new Vue({
data: {
count: 0,
state: 'I will …
```

Enable "state" as a valid key in getters

---

types/index.d.ts

watch callback gives oldValue as the second parameter.
It may also be undefined in case `{immediate: true}` is used, but typing it optional could be inconvenient for most common uses.

Update store.watch() typing

---

docs/en/testing.md
docs/fr/testing.md
docs/ja/testing.md
docs/ru/testing.md
docs/zh-cn/testing.md

update testing doc: commit to mutation not dispatch

---

docs/en/modules.md
src/index.js
src/module/module-collection.js
src/module/module.js
src/util.js
test/unit/jasmine.json
test/unit/module/module-collection.js
test/unit/module/module.js
test/unit/test.js
types/index.d.ts
types/test/index.ts

This PR is an implementation of #380 with update for docs and typings.
- Modules can have `namespace` option that expects `string` value.
- This option allows us to add prefix for all getters, actions and mutations in the same module, and also can inherit or nest a parent prefix (https://github.com/vuejs/vuex/issues/380#issue-181871602).
- `getters`, `dispatch` and `commit` in a namespaced module's action context will be localized. i.e. implicitly add module's namespace on their execution (https://github.com/vuejs/vuex/issues/380#issuecomment-252629629).
- `dispatch` and `commit` can receive `root` option on their last argument. If `root` option is specified, they dispatch/commit on global level (See example code in https://github.com/vuejs/vuex/issues/380#issuecomment-252629629).
- …

Implement module `namespace` option

---

dist/vuex.js
src/index.js
test/unit/test.js

* the first parameter of store.watch(), which is a function, now receives the store.getters object as its second argument.
* added unit test
Fullfills request #460

Add store getters as second argument to store.watch() computed fn (solve #460)

---

src/helpers.js
src/index.js
test/unit/helpers.spec.js

I noticed that the local state in the mapState helper will not be updated sometimes.
e.g. when using replaceState (https://jsfiddle.net/vx5092oa/)
This is because it refers to state option object in each module rather than the actual state tree.
I added state property in the local context that refers the state sub-tree. Also it can simplify module registration a little :)
/ping @yyx990803

Adjust mapState helper to refer to actual state

---

docs/en/intro.md

Specify `v2` to the url, or the anchor will be removed because of the redirection.

Fix the link of `global event bus`

---

docs/en/modules.md

The current description of module actions:
> Similarly, inside module actions, `context.state` will expose the local state, and root state will be exposed as `context.rootState`:
However `context.rootState` does not appear in the original example code, which might confuse some readers. The proposed change appends `rootState` to the argument list and make use of it in the action.
Also, I'm not quite sure about the new method name: `incrementIfOddOnRootSum`. So please suggest alternatives if possible.
/cc @yyx990803

Add rootState to module action's example code

---

docs/zh-cn/actions.md

The first thing to know is that store.dispatch can handle Promise returned by the triggered action handler and it also returns Promise:
旧：第一件事你需要清楚的是 store.dispatch 的返回的是被触发的 action 函数的返回值，因此你可以在 action 中返回 Promise：
新：首先，你需要明白store.dispatch可以处理被触发的action的回调函数返回的Promise，并且store.dispatch仍旧返回Promise。

Action的文档，有一条翻译不准确。

---

docs/en/getting-started.md

The example on jsfiddle is broken. We need to update the external resources

fix jsfiddle example

---

docs/en/getters.md

Add possibility to return functions in getters (https://github.com/vuejs/vuex/issues/598)

Update getter docs

---

src/index.js
test/unit/test.js

As pointed out in #538, we may register `undefined` mutation and accidentally dispatch it if we have typo in constant types.
I've added assertion in dispatch method to avoid and can be aware the mistake.

[v1.0] Assert dispatched type

---

src/index.js
test/unit/modules.spec.js

Just skipping `oldVm.state = null` when store resetting is caused by `registerModule`.

Avoid to fire unrelated watchers with registerModule (fix #524)

---

docs/en/modules.md

Maybe I misunderstood the example, but without parenthesis the `%` operator will be executed before the `+`.

Mini fix in rootState example.

---

docs/ja/getters.md
docs/ja/modules.md

Just translated #601 and #634 into Japanese 🙂 
/ping @kazupon

Update ja docs

---

docs/en/actions.md

I was looking for this information, googled, and landed in #611. 
So I opened this PR to add a line to the docs that explains this.

Explain that `mapActions` supports payloads

---

docs/en/getters.md
docs/ja/getters.md
docs/ru/getters.md

I believe this is a minor error in one of the getters docs examples.  I changed it in the en, ja & ru language files. I did not see same example in the other language files.

Fix minor error in getters docs example

---

docs/fr/state.md

Mistake around 'avec' and 'avoir'.
'avec' is 'with' in english, and 'avoir' is 'have'.

Fix translation

---

src/store.js
test/unit/helpers.spec.js

Fix #708 
If the store has a namespaced module X that has a non-namespaced module Y, `mapState` helper can get a wrong state.
This is because X and Y has the same namespace due to inheritance. Then module X in `_modulesNamespaceMap` is overwritten by Y.
This PR limits only `namespaced === true` modules can be registered in `_modulesNamespaceMap` to avoid this behavior.

avoid to get wrong state with mapState

---

docs/en/testing.md

When copy / pasting the webpack configuration given in the 'Testing' doc page, I end up with following error:
`ERROR in Entry module not found: Error: Can't resolve 'babel' in '<...>'`
`BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.`
`You need to specify 'babel-loader' instead of 'babel'.`
My version of webpack: 2.2.0-rc.3
Adding the '-loader' suffix fixed the problem.
Not sure though how safe it is to use 'babel-loader' instead of 'babel' with previous webpack versions...

Testing doc page - Add '-loader' suffix to webpack config

---

docs/en/api.md

It missing rootGetters for the getters definition in API.

Improve module getters definition

---

docs/en/mutations.md

Added an example of passing a payload to a mutation when using the `mapMutations` helper. This is [included in the documentation on actions](https://github.com/vuejs/vuex/blob/dev/docs/en/actions.md#dispatching-actions-in-components), so thought it would be a good idea to keep the two pages consistent.

Added example of passing payload to mutation with mapMutations helper

---

dist/logger.d.ts
docs/en/plugins.md
docs/fr/plugins.md
docs/ja/plugins.md
docs/kr/plugins.md
docs/ru/plugins.md
docs/zh-cn/plugins.md
src/plugins/logger.js

Add filtering of the mutations logging

---

docs/fr/installation.md

We are the [Vue-FR](https://github.com/vuejs/vuejs.org#french) team. We provide our review on Vuex translation part (with cross consistency from others Vue documentations).
**Fell free, if you prefer, to accept this pull request when all (or a lot of) pages will be translated but this pull request will help others translators to not done the translation twice**.
French review:
- Review of `README.md` done.
- Review of `installation.md` done.
Process:
- We will track all futur modification from `en` directory because in our `working` branch we use the `en` directory to work. All futur `en` modification at an already translated position will warns us with a conflict.
- We reverse all work done from `:working/en` to `:dev/fr` and we will provide some pull request each time a set of pages …

[Translation] Official French Translation from Vue-FR

---

docs/en/testing.md

When an error occurs in an assertion, you receive the message that your promise hook was not closed within 2 seconds.
By catching the error, we can call done(error) (this works for standard vue-cli template)
1. This makes sure the test is properly closed
2. The assertion error is logged to the console

Add a try-catch to the testAction helper method example

---

examples/todomvc/components/App.vue
package.json
yarn.lock

see tastejs/todomvc-app-css#8.
`todomvc-app-css` upgraded version to `2.1.0`, `"todomvc-app-css": "^2.0.6"` in vuex's package.json will download latest version, `.toggle-all` class has a big change, causing it to be hidden in todomvc example.

fix .toggle-all checkbox was hidden

---

docs/en/getters.md

It's important to kept consistency accross documentation to allows translation to be done number line by number line.
So each new line can be separate by a free line !

Doc EN `getters.md` : Add new line for consistency

---

src/helpers.js
src/index.esm.js
src/index.js
test/unit/helpers.spec.js

When using namespaced Vuex module with Vue components, binding namespace to the helper functions (mapState, mapGetters, mapMutations and mapActions) is a bit verbose. For example:
```js
const storeModule = new Vuex.Store({
namespaced: true,
state: { val: 0 },
actions: {
someAction() {},
},
})
modules: {
foo: storeModule,
},
})
new Vue({
store,
state: { str: 'abc' },
computed: {
// I split up these two state mapping to take advantage of array syntax
...mapState('foo', ['val']),
...mapState('foo', {
newVal(state) {
return state.val + ' ' + this.str
},
})
},
methods: {
...mapActions('foo', ['someAction']),
someOtherMethod() {},
},
})
```
You can see how many times I have repeated to do the binding job to integrate the Vue component with the module assets.
So I …

feat: add `createNamespacedHelpers()` to help dealing with namespaced modules

---

docs/en/actions.md
docs/en/modules.md
docs/en/mutations.md
docs/en/plugins.md

Some consitency enhancement proposed after french translation.

Improve documentation consistency for `mutations.md` and `actions.md`

---

src/mixin.js

场景：
组件树：(R为根组件；C1为R的子组件；C11、C12为C1的子组件， C11，C12下面还有很多下层组件)
R
|___C1
　　|____C11
　　|____C12
|___C1
　　|____C11
　　|____C12
|___C1
　　|____C11
　　|____C12
C1的每个实例的数据显示是不一样的， 如果使用props传递数据，将会导致所有组件的实例要知道自己的index，不然不知道去修改哪个state。如果vuex支持延时创建store，那么在C1 上面延时生成store，下层组件使用$store的时候，不需要关心当前是哪个store的。

vuex 支持延迟生成store

---

docs/en/modules.md

Add an example when we want to create multiple stores that uses the same module in the module reuse section. I seem that it is mainly for SSR purpose, isn't it?
Fix #807

Mention how to avoid stateful singletons in SSR (fix #807)

---

types/index.d.ts

With clear JavaScript Vuex.Store I can use logic like this:
```javascript
const myListStore = new Vuex.Store({
state: {
list: []
},
mutations: {
addItem: function (state, item) {
state.list.push(item);
}
},
actions: {
getItemById: function (action, itemId) {
return new Promise(function (resolve, reject) {
for (var i in action.state.list) {
if (action.state.list[i].id == itemId) {
resolve(action.state.list[i]);
return;
}
}
reject();
});
}
}
});
```
Using TypeScript it will be:
```typescript
const myListStore = new Vuex.Store<MyStateInterface>({
state: {
list: []
},
mutations: {
addItem: (state, item: MyItemInterface) => {
state.list.push(item);
}
},
actions: {
getItemById: (action, itemId: number) => new Promise<MyItemInterface>((resolve, reject) => {
for (let i in action.state.list) {
if …
```

dispatcher typescript declaration fix

---

docs/en/getters.md

In review getters docs, it was not clear whether the results of a getter were cached. This is alluded to in the remark "think of them as computed properties for stores", and in [reviewing the source](https://github.com/vuejs/vuex/blob/7409d4f6aa36d3de13de96dd7a953ad17ea3575a/src/store.js#L215-L232) it's seen that they are in-fact computed properties under the hood, but I think the docs could benefit from describing this behavior more explicitly. In fact, this alone is a compelling feature of Vuex, as unlike Redux which requires a library like [Reselect](https://github.com/reactjs/reselect) (or my own [Rememo](https://github.com/aduth/rememo)), Vuex has caching built-in to its selector equivalents.

Docs: Clarify getter cache behavior

---

src/mixin.js

- [rename: init -> beforeCreate](https://github.com/vuejs/vue/commit/8c869731988a2bb961955a4c896227977acb4c3d) in v2.0.0-alpha.7
- it's not necessary in the next version

Proposal: remove usesInit condition

---

docs/en/hot-reload.md
docs/en/plugins.md
docs/en/testing.md

- No usage of lower capital to « webpack » word fix (even as starting word
- — see https://webpack.js.org/configuration/ for phrase majuscule example 
- — see https://webpack.js.org/development/release-process/ for link/title example)

Doc EN: Webpack to webpack

---

package.json

Continue reducing vue modules size, started in https://github.com/vuejs/vue/pull/6072. Removing `src` directory reduces size of installed `vuex` package by 33% (96kb instead of 144kb)

Remove `src` directory from npm module

---

types/index.d.ts
types/test/index.ts

On the subscribe function, the mutation object was only having the `type` property and missing the payload

Add MutationPayload type

---

src/store.js

As of vue's `runInNewContext` enhancement for SSR, everything should be stateless in server side to prevent each request affecting others so when implementing Actions which need access to `ssrContext` (Like axios with configured proper auth headers - nuxt-community/modules#26) the only way is passing those references from caller as action/mutation parameters ([example](https://github.com/nuxt-community/modules/tree/master/modules/axios#store-actions)), this is working but makes usage ugly and really harder. This enhancement is required for workaround and fixes by simply binding handlers to store instance. So we can inject state into store and access it using `this` inside action/mutation functions. (`this` is currently undefined inside handlers)

feat(store): bind mutation and action handlers to store

---

src/store.js

Vuex always connects vue-devtools currently but it would not make sense if devtools is disabled via Vue's config.
This PR let devtoolPlugin be disable if `Vue.config.devtools === false`
Fix #875

perf: do not connect devtools if Vue.config.devtools == false

---

test/unit/helpers.spec.js

因為一直 [vuex] module namespace not found in mapGetters() 找不到原因是為啥。
去看測試，發現沒有 nested 的測試案例，就寫了個。
寫完跑完發現會過... 原來是我代碼太多層有一層忘了加 namespaced: true...

Add a testcase for mapGetters (with namespace and nested module)

---

docs/en/api.md
docs/en/modules.md
types/helpers.d.ts
types/test/helpers.ts

I noticed that typings and documents of `createNamespacedHelpers` (ref #800) are missing. This PR adds them.
In addition, I've refactored `mapXXX` helpers' typings to declare the namespaced helpers without redundancy.

fix: add missing typings and docs of createNamespacedHelpers

---

types/index.d.ts

Corrected the return type of the `Store#watch` method in the typescript typings.

fix(typings): watch() returns an unwatch function

---

src/helpers.js
test/unit/helpers.spec.js
types/helpers.d.ts
types/test/helpers.ts

This is a small improvement for `mapActions` and `mapMutations` helpers. It allows users to pass functions in the helpers so that reducing some redundant method definitions. The feature is like a counterpart of passing function in `mapState`.
For example:
```js
const vm = new Vue({
store,
template: `<input @input="onInput">`
methods: mapActions({
onInput (dispatch, event) {
// First argument is as same as this.$store.dispatch
dispatch('inputText', {
text: event.value
})
}
})
})
```
The above code is equivalent with the below (Note that `inputText` is a bit redundant since it is just an bridge method between `onInput` and the action):
```js
const vm = new Vue({
store,
template: `<input @input="onInput">`
methods: {
...mapActions(['inputText']),
onInput (event) {
this.inputText({
text: …
```

feat: allow to passing functions in mapActions/mapMutations (fix #750)

---

src/store.js

While auto-calling `Vue.use(Vuex)` is convenient for users who use Vue/Vuex via `<script>`, there are a case that users want to avoid the behavior when `window.Vue` is exists (See #731).
Currently, Vuex is immediately installed into `window.Vue` when Vuex is imported. So there are no way to install Vuex into `import`ed Vue.
To solve this, I'd move it in `Vuex.Store`'s constructor. Then the auto-installation is delayed until users create a store and the users can install Vuex into their own Vue constructor before doing it.
I'm not sure how to write test code for this but it looks like working well.
fix #731

fix: move auto installation code into the store constructor

---

docs/kr/testing.md

actionsInjector 를 불러올 때 inject-loader의 inject 예약어는 더이상 지원하지 않는다고 하네요.
require('inject!./actions')   >>  require('inject-loader!./actions')

inject-loader 예약어 수정

---

src/store.js

Just a moment ago I had hard time debugging this code:
```js
const state = () => {}
...
new Vuex.Store({
state,
modules,
...
})
```
If state is `undefined` and you use modules, Vuex can't create store. This small change will make it easier to find this error.

fix: initialize root state as an empty object if state function returns no value

---

docs/en/api.md
docs/en/modules.md
src/store.js
test/unit/modules.spec.js
types/index.d.ts
types/test/index.ts

As speaking with @TheLarkInn we where saying it would be awesome to be able to register a module dynamically to be able to code split the store in a large application. 
It is totally possible with `store.registerModule('a', module)`. Here is an example, if using hooks to ensure prevent the route loading. This can be achieved with `asyncData` with client mixins and global hooks. https://ssr.vuejs.org/en/data.html
```js
export default {
async asyncData ({ registerModule, dispatch }) {
registerModule('a', await import('@/store/modules/a'))
dispatch('a/action')
}
}
```
The issue with this with SSR this would replace the pre-populated data. This pull request aims to fix this scenario.

feat: preserve state with registerModule

---

docs/en/plugins.md
docs/fr/plugins.md
docs/zh-cn/plugins.md
src/plugins/logger.js

Similar redux-logger, add custom console implemenet [redux-logger#options](https://github.com/evgenyrodionov/redux-logger#options)
for example, I can use it like this:
-> logger.js
```js
const doConsole = (level, ...args) => {
if (typeof console === 'undefined') return;
const fn = console[level]; // eslint-disable-line no-console
const isDev = process.env.NODE_ENV !== 'production';
const enableByLocalStorage = typeof localStorage !== 'undefined' && 
localStorage.getItem('enable_production_log');
if (fn && (isDev || enableByLocalStorage)) {
fn.apply(console, args);
}
};
export default [
'debug',
'error',
'info',
'log',
'warn',
'dir',
'table',
'trace',
'group',
'groupCollapsed',
'groupEnd',
].reduce((result, current) => ({
...result,
[current](...args) {
return doConsole(current, ...args); …
```

feat: add logger plugin logger config support

---

src/store.js
test/unit/modules.spec.js
test/unit/store.spec.js

Allows to listen dispatched actions
After feedback from https://github.com/vuejs/vuex/pull/929 so we can implement #908
API is as suggested by @ktsn 
```js
function actionLoggerPlugin(store) {
store.subscribeAction(({ type, payload }, state) => {
console.log(`Before dispatching "${type}" with ${JSON.stringify(payload)}`
})
}
// ...
plugins: [actionLoggerPlugin]
})
```

feat: subscribeAction

---

docs/zh-cn/SUMMARY.md
docs/zh-cn/api.md
docs/zh-cn/modules.md

ref: `/docs/en/*` parts of https://github.com/vuejs/vuex/compare/b206933...bb76bfd

[zh-cn] synced from #b206933 to #bb76bfd

---

docs/fr/getters.md

« Il ne sera évalué _que_ quand… » and maybe better « Il ne sera évalué _que lorsque_… »

Fixed missing word in getters.md

---

docs/fr/actions.md

The title was wrong this section is not related to dispatch actions in components.

Fix wrong title in french translation

---

src/store.js
test/unit/store.spec.js

fix #1030 
Just using the state object of module instead of manually calling the function in the store constructor.

fix: avoid to call root state function twice

---

examples/shopping-cart/store/modules/cart.js

inside [types.ADD_TO_CART] ...
state.lastCheckout = null // seems to do nothing
state.checkoutStatus = null // this makes more sense, hides checkout-msg when new item gets added to cart

shopping-cart example: 'lastCheckout' should be 'checkoutStatus' to have any impact

---

docs/en/getters.md

In the current getter example, there is no need of including `getters` dependency as we are not using it while defining the method to search by Id, `getTodoById`

Unused paramater : getter

---

docs/en/actions.md

> Actions don't
Did not make sense.

wording did not make sense.

---

docs/en/api.md

Description of the `watch()` function is not accurate, [getter receives two arguments](https://github.com/vuejs/vuex/blob/dev/src/store.js#L150).

docs: update watch() description

---

types/helpers.d.ts
types/test/helpers.ts

Relax `this` used in `mapState` helpers. If user want more specific typing, they need manual annotation.

fix: fix #1032, relax vue typing in helpers

---

docs/en/getters.md

I've been using Vuex for about a year, and I never realised you could access store getters as methods.
This docs update makes the ability to do this explicit, as well as adding notes on caching.

Made getter property vs method syntax more explicit

---

docs/en/api.md

* Changed the wording of `store#watch`'s 1st argument. It was actually a getter function until v1.x but the current getter is not a simple function. (fix #1141)
* Added descriptions how to unsubscribe from `subscribe` / `subscribeAction`. (fix #1194)

docs: improve API reference of watch and subscribe

---

docs/en/testing.md
docs/fr/testing.md
docs/ja/testing.md
docs/kr/testing.md
docs/zh-cn/testing.md

This makes it read & produce the correct error messages
It now reads as `expect(actual).to.equal(expected)`

docs: Update docs of testAction helper

---

types/index.d.ts

- while testing we have methods using this method signature and it would be nice if we did not have define this.
We were running into the issue as reported in https://github.com/Microsoft/TypeScript/issues/7960
So workaround was to do something like
```
type ModuleAction<ModuleState> = (injectee: ActionContext<ModuleState, State>, payload: any) => any;
const loginAction = userActions.login as ModuleAction<UserState>;
```

export ActionHandler

---

docs/kr/api/README.md

In Korean document(API - Vuex.Store Contructor options part), there was an typo (로투).
It should be fixed as 루트(root).
thanks.

Fixed API document (Korean) typo

---

types/index.d.ts
types/test/index.ts

The handlers for actions and mutations are bound to the store, but there is no type annotation for this behavior. 
This PR will enable us to use `this` as Store in the handlers.

feat: add type annotation for the context of actions and mutations

---

docs/guide/modules.md

Guide suggests that these two example are equal, and are different only by syntax. But they are different, and it would be good to clarify that.

docs: Clarify example with namespaced actions

---

examples/shopping-cart/components/ProductList.vue
examples/shopping-cart/components/ShoppingCart.vue

Updates:
---
- Add key to v-for

fix: Add key to v-for

---

types/index.d.ts

Partially based on #1274
Import Vuex.
```ts
import Vuex from "vuex";
```
Using before this PR: 
```ts
(Vuex as any).mapActions(...)
```
Using after:
```
Vuex.mapActions(...)
```

Add helpers to default export type declaration as in sources

---

types/index.d.ts
types/test/index.ts

This PR allows to pass a function for root `state` option as same as modules in TypeScript.

fix(types): allow a function type for root `state` option

---

docs/api/README.md
src/store.js

This PR adds the ability to turn off devtools on a per vuex instance level.  This is useful for cases where you have multiple vuex stores on a single page.  A good example is a scenario where teams maintain their own portions of a single app that are all loaded, some of which will have an independent vuex store.
With this option, on the dev side i could turn this off per instance so that I can debug a single store. 
By default, this mirrors what is already in vuex, it just allows for turning off when specified.
```
devtools: false
})
```
Follow through on https://github.com/vuejs/vuex/issues/875

Add ability to turn off devtools on vuex by passing an off options

---

docs/zh/api/README.md

Ref: https://github.com/vuejs/vuex/compare/b205e9f...f64a89c
/ping @justineo
Thanks.

docs(zh): updated to #f64a89c

---

docs/api/README.md

> Accepts an optional options object that takes the same options as Vue's vm.$watch method.
linking to the actual `watch` of the vue doc might be helpful for others to check options faster. not sure if this is wanted though due to future maintenance efforts.

chore(docs): link to vue docs watch for options

---

docs/guide/mutations.md

The stage of [object spread syntax](https://github.com/sebmarkbage/ecmascript-rest-spread) has been changed to 4

Makes the document more stable by removing stage-x for object separate syntax while it can be changed in the future

---

docs/guide/modules.md

"You can ~do~ achieve this" -> "You can achieve this"

Eliminate extra word

---

docs/guide/actions.md

Although it is mentioned further down the document; I think this line will make it more clear especially for newcomers of vuex. I see similar questions regarding this like https://stackoverflow.com/questions/45848974/call-an-action-from-within-another-action

Added copy to clarify context

---

docs/.vuepress/components/VideoPreview.vue
docs/README.md

... for better maintenance and translation.
Ref: https://v0.vuepress.vuejs.org/guide/using-vue.html#using-components
Thanks.

docs: replaced video preview code to a VideoPreview component

---

docs/api/README.md
docs/zh/api/README.md

In ["API Reference" > "Vuex.Store Instance Methods" > "watch"](https://vuex.vuejs.org/api/#watch) section of the `en` docs, there is a link of "Vue's `vm.$watch` method" but linked to `watch` options. It should be https://vuejs.org/v2/api/#vm-watch if I don't misunderstand it.
I also fixed the `zh` docs. And the `ru` docs seems right. but other language docs seems not same to the latest `en` version. So I am not sure whether should be updated too.
Thanks.

docs: fixed links to vm.$watch

---

docs/ptbr/guide/modules.md

Hi!
I noticed a english paragraph forgotten  in the guide translated,
the pr is just to fix.

docs: Removed english from translated guide [pt-br]

---

docs/guide/modules.md
docs/ptbr/guide/modules.md

It is not very clear the purpose of `preserveState` option in the docs. 
[This comment](https://github.com/vuejs/vuex/issues/1130#issuecomment-356612119) clarified the behavior, so I included in a dedicated `preserveState` subsection.

docs: complement preserveState information

---

package.json

see difference here:
- https://cdn.jsdelivr.net/npm/vue/package.json
- https://cdn.jsdelivr.net/npm/vuex/package.json

support jsdelivr npm cdn like vue package does

---

docs/.vuepress/config.js

👋 vuex,
I am [working on DocSearch](https://community.algolia.com/docsearch/), this PR will enable vuex to use the same search [experience as vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search), [vuejs](https://vuejs.org/), [bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/) ...
Our scraper will run every 24H to update your Algolia index. Feel free to [PR your configuration](https://github.com/algolia/docsearch-configs/blob/0b171ddf626dac501b2d9bf4a80e79613c874918/configs/vuex.json) if you need any update, the search is out of the box.
Let us know if you need anything.

doc: Enabling DocSearch

---

src/plugins/devtool.js

This allows inspecting vuex state in standalone devtools with non-browser environments such as NativeScript
Changes taken from
https://github.com/vuejs/vue-devtools/blob/4fe7c84d614f1ddf581d65274f30a989b77f9ad3/shells/electron/index.js#L3-L7

feat(devtool): allow usage in non-browser environments

---

docs/fr/guide/state.md
docs/zh/guide/state.md

doc: change ECMASCript into ECMAScript

---

types/index.d.ts

When testing a mutation without payload in TypeScript, it complains that about the missing payload, even though it's not mandatory.
This PR simply makes the payload optional.
Fixes #1491

Make mutation and action payload optional in definition file

---

docs/guide/actions.md

Replace "dumb" with "silly", since dumb [is defined as mute or unable to speak](https://www.dictionary.com/browse/dumb). What the implies is this function call may seem to be a bit extra and non obvious at first glance. 
The whimsical word "silly" is a nice stand in for this.

docs(en) Small phrase improvement: silly

---

docs/guide/state.md
docs/ptbr/guide/state.md

Clearify in the docs that Vuex state object should be a plain object that follows the same rules as `data` in a Vue instance. This addition will clarify what is "good practise" to use in Vuex.
closes #1587 
closes https://github.com/vuejs/vue/pull/10379

fix(docs): Clearify state object type

---

docs/zh/guide/modules.md

fix typo in zh docs of `modules`

docs(zh): fix typo

---

src/helpers.js
test/unit/helpers.spec.js

- return an empty array when map is not valid
- log an error message when map is not valid

Should vuex mapState print error message #1093 #1162

---

src/store.js
test/unit/modules.spec.js

Warn about conflicts between state and module

---

package.json
types/helpers.d.ts
types/test/helpers.ts
yarn.lock

fix(types): avoid broadening vue instance type when using map helpers

---

src/helpers.js
test/unit/helpers.spec.js

fix: tweak mapping helper warning message

---

examples/todomvc/store/mutations.js

Issue #1591
This PR refactors the mutation logic in todo example to not mutate mutation payload directly in the simplest form.
It's still using the reference to todo (at `indexOf`) but I think it's more clearer than before that Vuex recommends to not mutate payload directly.

#1591 refactor: do not mutate mutation payload in the todo app example

---

docs/guide/forms.md
docs/zh/guide/forms.md

I think this 'action' maybe is not the action in Vuex? Maybe using 'mutation' in docs is more specific
I check the englinsh docs, and it's the same word 'action'...
Maybe I misunderstand the mean

fix docs description

---

package.json

Issue: #1681 
This PR adds Vue as a peer dependency. It should help using Vuex with Yarn 2 too.

build: add vue as a peer dependency (#1681)

---

docs/guide/modules.md

As we browse through the modules page, it is unclear where the `store` is imported from.
Since it is a one liner, I thought it would clarify to have the import explicitly here.
Tell me what you think.

docs: make obvious where to import store from

---

docs/api/README.md
docs/guide/modules.md
types/index.d.ts
types/test/index.ts

This PR adds docs and typing for the new `hasModule` API which was added at #834.

docs: add docs and typings for the new `hasModule` method

---

.github/commit-convention.md
.github/contributing.md
CHANGELOG.md
README.md
build/release.sh
package.json
yarn.lock

This PR adds Conventional Changelog support to enhance release process and to align with recent Vue ecosystems.
- Generate initial CHANGELOG.md including all past releases.
- Add Contribution guideline taken from Vue & Vue next. The contents are modified slightly to fit into Vuex context.
- Update release shell file to support changeling generation.

build: add conventional changelog support

---

docs/guide/README.md

_Note:_ This change was already introduced in #858 and it's still crucial for Vuex docs but since this PR exists for 1.5 years and has conflicts with a base branch, I'm opening a new one.
Added a short description of how to provide a store to Vue instance to have access to it from inside Vue components.
**Update:** found docs on injecting store in the `State` doc. I still think they should be moved to `Getting started` part because it's just easier not to miss it in the entry doc.

docs: add a description of providing store to Vue instance

---

docs/guide/testing.md

Here is my example code:
```javascript
test('commits setContributionId', (done) => {
const state = {
comments: []
}
testAction(action, 42, state, [
// ...
{ type: 'isLoading', payload: false}
], done)
})
```
I'm passing `42` as an argument to `testAction` and I want to verify that `commit('isLoading', payload)` is executed. Here the payload is not the payload of the testAction helper (in my case 42) but the second argument of `commit`. That might be `false` and in my case it is. If I change the payload of the last expected commit to be `true` no assertion error is raised. The fix is to make the if condition in the mocked commit method more specific.

Fix false negative when checking `payload: false`

---

docs/ja/api/README.md
docs/ja/guide/modules.md

This PR add the Japanese translation for the new `hasModule` API.

docs(ja): add `hasModule` api translation

---

dist/logger.d.ts
docs/guide/plugins.md
src/plugins/devtool.js
src/plugins/logger.js

Allow `createLogger` to optionally log actions, added a couple of options
```js
{
actionFilter,
actionTransformer,
logActions,
logMutations
}
```
~With some sane default to keep current functionality by default, this would be an opt-in option.~ Enabled by default as requested.
When enabled you get something like:
It just logs the action type and payload, since we cant tie actions to mutations, which I think its ok.
Note: Also added the `devtoolHook` for actions so we can hook it up later with devtools.
PS: I'm about to do a small plugin in case this proposal doesn't get approved and will update this PR with the url just in case someone is looking for this functionality. It would be awesome if we could have it built-in tho.

Proposal: createLogger can optionally log actions

---

types/index.d.ts
types/test/index.ts

This PR adds missing types for subscribe `prepend` option merged via #1358.

types: add subscribe options type

---

docs/ja/api/README.md
docs/ja/guide/plugins.md

This PR adds the Japanese translation for the new options added to `subscribe` methods and logger plugin.

docs(ja): translate new options for the `subscribe` methods and logger plugin

---

README.md

To work global typings for `this.$store` need to import `Store` and `ComponentCustomProperties`

fix: import requirements for  `this.$store` in README

---

types/index.d.ts
types/test/index.ts

fix #1736
This PR adds missing `useStore` function typings. Users may provide `State` as a generics, or use without it to get `Store<any>` type.

types: add `useStore` function (#1736)

---

docs/api/README.md
docs/fr/guide/modules.md
docs/guide/modules.md
docs/ja/guide/modules.md
docs/kr/guide/modules.md
docs/ptbr/guide/modules.md
docs/ru/guide/modules.md
docs/zh/guide/modules.md
examples/shopping-cart/store/modules/cart.js
examples/shopping-cart/store/modules/products.js

This PR replaces all state declaration as functions for [module](https://vuex.vuejs.org/guide/modules.html) examples only.
Leading by example, pun intended, this will encourage users to avoid common pitfalls with shared declarative state.
Instance state examples are retained as `Object` since this does not apply to root state.
Closes #1477

docs: module state declaration as function

---

docs/api/README.md

Add API docs for the new `error` option added to the `subscribeAction` method via #1740.

docs: add docs for the new `error` option for `subscribeAction` method

---

docs/guide/hot-reload.md

I have looked for a way to load and hot reload Vuex modules systematically, rather than specifying them explictly.
Adapted from: https://github.com/kazupon/vue-i18n/pull/865

docs: add Dynamic module hot reloading example

---

jest.config.js
src/store.js

Replaces the orphaned `process.env.NODE_ENV` with the new global `__DEV__`.

refactor: remove node env flag

---

docs/zh/guide/README.md

docs: Fix missing information in the guide.

---

test/unit/util.spec.js

This PR
💁‍♂️ I'm new to `vuejs` and `vuex`, so I'm not sure if this makes sense - but I could not find any documentation on what would be returned when an item is not found. What do you think?

Fix: Document return value when item was not found

---

src/index.cjs.js
src/index.js
types/index.d.ts
types/logger.d.ts
types/test/index.ts

This PR add `logger` plugin to the core export to be able to support ESM build for the `logger` plugin. Issue was mentioned at https://github.com/vitejs/vite/issues/334.
This is for Vuex 3, so I'm keeping the individual bundle as is to avoid braking change. For Vuex 4, I'm planning to remove the logger bundle entirely.
Planning to follow up the PR with documentation update as well for the next release.

feat: include logger plugin to the core export

---

docs/guide/plugins.md

This PR updates the `logger` export in the docs.
Ref #1783

docs: update the new `logger` plugin export path

---

src/module/module-collection.js
test/unit/module/module-collection.spec.js

close #1426
This PR adds warning when removing non existing module. Currently, it fails due to `runtime` not exist in `undefined` error. It's follow up PR for #1426.
It will only warn in development mode, so it will not introduce any braking changes.

fix: warn when unregistering non existing module

---

docs/kr/README.md

Remove duplicated parenthesis of link to "Scrimba" in Korean README markdown file.

docs: fix link typo in Korean README

---

docs/guide/modules.md

Hey,
I just found myself looking up the exact syntax, so I'd like to contribute these examples.
Best regards,
Micha

docs(guide/modules): Add examples for getters in other namespaced modules

---

types/index.d.ts
types/test/index.ts

This PR adds lost argument `key` to `useStore` function types.
Resolve #1807

fix(types): add lost argument of useStore

---

docs/guide/state.md

The period should be inside the quotations, not outside the quotations.

docs(typo): fix punctuation

---

docs/ja/api/README.md

The "d" did not exist at the heading of `createNamespacedHelpers` in ja doc.

docs(typo): fix incorrect createNamespacedHelpers name in ja

---

docs/api/README.md

I added a warning text to the docs about remembering to call `unsubscribe` when subscribing to the store.

docs: warn about calling unsubscribe (fix #1050)

---

types/logger.d.ts
types/test/index.ts

* createLogger options takes in logger which by default is console but
can be overridden with own logger.
* Adding Ilogger for logger options params which expects log method to
be implemented

feat(types): adding logger type for logger plugin

---

src/store.js

Go to issue for full details
https://github.com/vuejs/vuex/issues/1823

[Repair] #1823 Getters are re-evaluated on every access

---

src/module/module-collection.js
test/unit/module/module-collection.spec.js
test/unit/modules.spec.js

This PR fixes issue #1850 .
If you call `store.hasModule()` with an array where none of the modules or submodules are registered in the store, an error is thrown instead of returning false:
```
TypeError: Cannot read property 'hasChild' of undefined
at ModuleCollection.isRegistered (/node_modules/vuex/dist/vuex.common.js:291:17)
at Store.hasModule (/node_modules/vuex/dist/vuex.common.js:611:24)
```

Check existence of module parent in isRegistered (fix #1850)

---

src/store.js

comment didn't update with the code.

docs(typo): fix typos in comment

---

docs/guide/getters.md
src/store.js

ref #1878 #1883
This PR temporarily fixes the issue where getters (`computed`) get destroyed when components get destroyed. The limitation is that with this fix, getters will get re-evaluated each time it gets accessed regardless of whether dependencies have got updated or not.
It's not an ideal fix, but we have to wait for Vue 3.1 release to fix this issue completely. Learn more at #1883.

fix: fix getters stop working when component is destroyed

---

package.json

fix #1909: single quotes cannot be identified in package.json of the Windows OS

---

docs/guide/typescript-support.md

The extension should be .ts instead of .js, since the file is in TypeScript.

docs(typescript-support): fix .js in comment

---

test/e2e/todomvc.spec.js

As `clear-completed button`  is part of `footer`, although we expect `await click('footer')` will trigger the `footer` element, however it actually triggered the `clear-completed button`, so the next asserts will failed. 4.0 branch has the same problem.
https://github.com/vuejs/vuex/blob/c9dbb13d4138d0e7d82d103dd3275fc18fa72d28/test/e2e/todomvc.spec.js#L123-L125
change click `footer` to `.todo-count` will make sure test cases pass, which could fix #1899.

test: todomvc case failed in windows and some linux os (#1899)

---

docs/guide/modules.md

fixes: #1781
Documents the nested modules requirement of being an array and not a string.

Clarify nested modules requirement for array in docs

---

rollup.config.js

fix #1991
I don't know if I changed it right
But I think __VUE_PROD_DEVTOOLS__ should be replaced to 'false' in the cjs mode.
There should be some small errors here.

fix(devtools): fix __VUE_PROD_DEVTOOLS__ defined in cjs build (#1991)

---

docs/installation.md
docs/ja/installation.md
docs/ptbr/installation.md
docs/zh/installation.md

Because Vue 3 doesn't support IE11 anyway, I thought we can remove the info regarding a `Promise` polyfill in the docs ☺️ 
I've removed the paragraph in all available languages

docs(installation): remove promise polyfill info

---

package.json
src/store-util.js
src/store.js
test/helpers.js
test/unit/modules.spec.js
yarn.lock

fix #1878
This PR aims to fix #1878, but at the moment this is just adding failing test case.
The problem we have is that when component gets destroyed, the getters (`computed`) get's destroyed via Vue. Hence if we call `registerModule` inside a component, any newly registered `computed` will disappear when that component gets destroyed, for example, when switching route.
The issue: vuejs/vue-next#1532
Solution RFC: vuejs/rfcs#212
We have to wait for Vue ~3.1~ 3.2 to completely resolve this issue.

fix: fix getters being destroyed on component destroy (#1878)

---

package.json

As mentioned in #2047 
Using the `"./": "./"` is being deprecated and it should be changed to `"./*": "./*"` in the future.
Adding both to the `package.json` will make it ready for the deprecation and remove the `DeprecationWarning` in the current version.

Fix deprecated warning in package.json export module (fix #2047)

---

docs/guide/composition-api.md

`commit` and `dispatch` are two methods of store
const store = useStore()
increment: () => store.commit('increment'),

docs: Change `funciton` to `method`

---

docs/guide/mutations.md
docs/zh/api/index.md
docs/zh/guide/actions.md
docs/zh/guide/forms.md
docs/zh/guide/getters.md
docs/zh/guide/modules.md
docs/zh/guide/mutations.md
docs/zh/guide/plugins.md
docs/zh/guide/testing.md
docs/zh/guide/typescript-support.md

based 7651d506e473886984eab625797477d63bc69981 commit, I updated zh docs from en docs

docs(zh): update zh docs from en docs

---

docs/.vitepress/config.js

Vuex's document, edit this page on GitHub, link to error.
This bug comes from the configuration issue with VuePress. The original configured document branch was 4.0, but this branch is no longer visible. 
This pr changed it to the default branch.
issue : https://github.com/vuejs/vuex/issues/2230

fix：error in Vuex document link

---

docs/guide/migrating-to-4-0-from-3-x.md
docs/guide/typescript-support.md
docs/ja/guide/migrating-to-4-0-from-3-x.md
docs/ja/guide/typescript-support.md
docs/ptbr/guide/migrating-to-4-0-from-3-x.md
docs/ptbr/guide/typescript-support.md
docs/zh/guide/migrating-to-4-0-from-3-x.md
docs/zh/guide/typescript-support.md

https://github.com/nuxt/nuxt/issues/28373#issuecomment-2373531197
This updates the docs to use the currently recommended way to augment component custom properties in Vue 3.

docs: augment `vue` rather than `@vue/runtime-core`
