vuejs/vuex

package.json
Fixes a compilation bug when using node v4.
=> Depends on vue-html-loader explicitly

docs/en/actions.md
#5 was for wrong branch, sorry for that :)
=> Tiny typo in actions.md

examples/shopping-cart/components/Cart.vue
Just to respect the arguments that the checkout option is waiting for:
```js
export const checkout = (products) => (dispatch, state) => {
const savedCartItems = [...state.cart.added]
dispatch(types.CHECKOUT_REQUEST)
shop.buyProducts(
products,
() => dispatch(types.CHECKOUT_SUCCESS),
() => dispatch(types.CHECKOUT_FAILURE, savedCartItems)
)
}
```
=> Send the products data in the checkout action

docs/en/actions.md
I think we want to update the `count` property on state object.
=> Update count property

docs/en/state.md
I am actually following the guide and missed a basic code sample like this...
=> state.md - code sample for state definition

docs/en/concepts.md
I spent some time figuring this out... https://github.com/vuejs/vuex/issues/68
=> concepts.md - include Vue.use(Vuex) call

docs/zh-cn/state.md
=> 更新了 state 文档

docs/zh-cn/actions.md
=> 修正mutation内操作state的行为

docs/zh-cn/testing.md
update testing.md's translation according to latest vuex versoin(0.6.2).
=> update testing.md's translation

docs/zh-cn/api.md
Update api.md's translation accroding to latest vuex version(0.6.2).
=> zh-cn docs patch

docs/zh-cn/state.md
原文在解释一些简单概念的时候，描述地很拗口，我适当简化了。
希望有更多人积极参与，不妥之处，敬请斧正 :)
译完 0.6.2 这个版本打算尝试理解 Vue/Vuex 源码 ~
=> zh-cn-docs-patch

docs/en/tutorial.md
Beside the fixed typos I would like to notice that there are inconsistencies with the rest of the docs.
- The code examples are not ES6
- Vue and Vuex mentions are written in lower case (fixed in PR)
- Some code examples are still in TODO state
- In general the speaking voice differs. Its obvious has been written by a different person
- There are no source files of the tutorial images
Is not my intention to criticize the efforts put into this tutorial but to point out those issues and offer my further assistance. I'm not native English speaker but could try improving the mentioned, if accepted.
=> fix minor typos

docs/it/mutations.md
I've added the new block that describe the silent dispatch.
=> Added silent dispatch to docs/it

docs/zh-cn/tutorial.md
=> modify tutorial.md code style

docs/en/middlewares.md
"we can format it any way we want."
=> "anyway" vs "any way"

docs/en/actions.md
Since no store argument is passed while calling `this.action()` in components, somebody may encounter with mistakes calling an action in another action by **not** passing the store argument (*that's true for me*).
Tips for action arrangement are added.
=> Tips for action arrangement

docs/it/data-flow.md, docs/it/forms.md, docs/it/getting-started.md, docs/it/mutations.md, docs/it/state.md, docs/it/strict.md, docs/it/testing.md
The title is self explanatory. I'll push more fixes next days if I'll have enough time to work on it.
=> Fixed some Italian typos.

types/index.d.ts, types/test/index.ts
I forgot to add types for nested modules on #218 ...
=> Update types for nested modules

src/index.js, test/unit/test.js
=> Expose getters into actions

docs/en/mutations.md
=> small word correction

docs/en/tutorial.md
Still learning Vuex. So let me know if i'm wrong
=> Fix wrong store state path

src/plugins/logger.js
=> [for 1.0] use state transformer in logger plugin

src/plugins/logger.js
ref #305 
This is same patch as #309 but for 2.0
=> [for 2.0] use state transformer in logger plugin

logger.d.ts, package.json, types/helpers.d.ts, types/index.d.ts, types/test/helpers.ts, types/test/index.ts, types/test/tsconfig.json, types/tsconfig.json, types/vue.d.ts
=> TypeScript declarations for 2.0

package.json, test/e2e/todomvc.js
Quick fix of the broken e2e test.
It seems that the current version of casperjs cannot trigger click events to hidden elements.
So the destroy button of each todo was not worked and the test was failed.
I have fixed this by triggering mouse move to appear destroy buttons.
=> Fix broken todomvc e2e test

src/index.js, test/unit/test.js
=> Support object style dispatch

docs/zh-cn/mutations.md
Actions not in Vuex.Store constructor options.
=> Api has chagned

docs/en/state.md
https://github.com/sebmarkbage/ecmascript-rest-spread
=> Rest Spread is now at Stage 3

docs/en/installation.md
Im not sure if this is a typo or not. This wording makes more sense to me as I am reading through your docs though. I use React a good bit in other projects.. Still getting used to Vue. Great work.
=> changed router to Vuex, as this isn't the router

docs/en/getters.md
add ... (spread operator) on map a getter to a different name section.
=> Missing ... (spread operator)

docs/zh-cn/structure.md
counter sample link target error.
=> [Docs] link target error

docs/en/mutations.md
The second `t` in `Comitting` was too silent.
=> Minor Typo Fix

build/rollup.config.js, package.json, src/index.js
Also added to vue-router https://github.com/vuejs/vue-router/pull/991
(Vue already has it)
=> Add version variable

.eslintrc, package.json, test/unit/.eslintrc
When I npm install'ed the dev branch, eslint threw up all over the place, so I added the (IMHO) missing config.
Does that seem alright with you guys?
=> Housekeeping eslint

docs/zh-cn/plugins.md
=> Update  plugins.md

docs/en/intro.md
Add a missing "the". So that "and Vuex will be natural next step for you", becomes "and Vuex will be **the** natural next step for you"
=> Correct typo

src/index.js, test/unit/store.spec.js
=> [v2.0] Assert dispatched/committed type

docs/en/modules.md
=> [docs] add a note that registerModule can receive an array of string

docs/ja/state.md
ブラウザで修正したので最終行に改行が入ってしまっていますが、修正した方がよろしいでしょうか？
=> 「オブジェクトスプレッド演算子」の構文間違えを修正

docs/fr/testing.md
Translate a sentence in a more natural way + add a missing verb in another sentence
=> Improve translation to testing.md

docs/en/api.md
=> describe options argument of dispatch/commit in api docs

docs/en/state.md
Standalone builds now are named as full builds
=> state.md standalone build -> full build

docs/en/actions.md, docs/en/modules.md, docs/en/mutations.md
Fixed via rephrasing slightly.
=> Minor language fixes.

examples/counter/store.js
=> fixed misspelling

docs/zh-cn/getters.md
translate getters cache feature from English version into Chinese
=> [zh-cn] translate getters cache feature from English version into Chinese

docs/en/state.md
=> Docs: Minor rephrasing in state.md

src/index.esm.js
=> refactor: export `install` as named export for tree shaking

docs/en/intro.md, docs/en/state.md, docs/en/testing.md
Change http link to https for Vue documentations.
=> [Doc EN]: http link to https

docs/zh-cn/api.md
=> [zh-cn] 将time-travel 更改为时光旅行，统一翻译

circle.yml
=> chore(ci): Use node 8

docs/fr/mutations.md
foncitons -> fonctions in french translation about mutations
=> French doc typo

docs/en/core-concepts.md
Changing 'this chapters' to 'these chapters'  and 'in Vuex' to 'of Vuex'.
=> Grammar fixes in core-concepts.md

docs/en/api.md
=> [en] added backquote for code in comments

docs/zh-cn/actions.md, docs/zh-cn/api.md, docs/zh-cn/getters.md
ref: `docs/en/*` part of http://github.com/vuejs/vuex/compare/bb76bfd...687962b
=> [zh-cn] synced from #bb76bfd to #687962b

docs/zh-cn/api.md
https://github.com/vuejs/vuex/compare/687962b...8fae0bc
/ping @Justineo
=> [zh-cn] synced from #687962b to #8fae0bc

docs/en/hot-reload.md, docs/en/plugins.md
The old documentation is no longer maintained.
=> Link to webpack 2 docs

docs/fr/hot-reload.md, docs/fr/plugins.md, docs/ja/hot-reload.md, docs/ja/plugins.md, docs/kr/hot-reload.md, docs/kr/plugins.md, docs/ru/hot-reload.md, docs/ru/plugins.md, docs/zh-cn/hot-reload.md, docs/zh-cn/plugins.md
=> [docs] #1097 for all languages

LICENSE
Uses the same template as in main repo to avoid recieving a PR every year.
=> Avoid updating license every year

types/index.d.ts, types/test/index.ts
Looks like this one slipped through the cracks, thanks for all the hard work!
=> Add subscribeAction in index.d.ts fixes #1066

docs/zh-cn/api.md
Very minor, tweaks for some Chinese expressions.
=> chore($docs): tweaks

docs/zh-cn/core-concepts.md
我们将会学到 Vue 的这些核心概念。 => 我们将会学到 Vuex 的这些核心概念。
=> Vue => Vuex

types/helpers.d.ts, types/index.d.ts
Small fix that adds missing semicolon and space in the typing files. Cheers 🍺
=> Add missing semicolon and space to the type files

docs/zh-cn/mutations.md
=> Remove unnecessary word in Chinese document

docs/zh-cn/api.md
#1173 Mention payload in action handler in API
/ping @Justineo 
Thanks.
=> [docs][zh-cn] translated #1173

docs/en/state.md
Ref: https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal
=> Update object spread operator stage

docs/zh-cn/getters.md, docs/zh-cn/state.md
Ref: https://github.com/Jinjiang/vuex/compare/dev...vuejs:dev
Thanks.
=> [docs][zh-cn] synced updates to #e237803

docs/ja/getters.md, docs/ja/state.md
=> docs: update Japanese docs

docs/kr/api.md
- Component Binding Helpers
- registerModule
=> [DOC KR] update updated Api description

docs/en/modules.md, docs/zh-cn/modules.md
[DOC ZH-CN EN] add description for feature(register global actions in namespaced modules)
=> [DOC ZH-CN EN] add description for feature(register global actions in namespaced modules)

docs/en/installation.md
=> docs: mention that vuex requires promise

src/store.js, test/unit/store.spec.js
- all throwing error should be starting with lower case
=> refactor: fix throwing error style

docs/en/api.md, docs/fr/api.md, docs/ja/api.md, docs/ru/api.md, docs/zh-cn/api.md
=> [docs] fixed text cut issue (close #1179)

docs/zh-cn/api.md, docs/zh-cn/installation.md, docs/zh-cn/testing.md
Ref: https://github.com/vuejs/vuex/compare/091c14f...57f3cb2
Thanks.
=> [docs][zh-cn] synced updates

examples/chat/api/index.js, examples/chat/components/MessageSection.vue, examples/chat/components/ThreadSection.vue, examples/chat/store/actions.js, examples/chat/store/getters.js, examples/chat/store/mutation-types.js, examples/chat/store/mutations.js
- remove mutation type
- use v-model instead of target.value
- use mapAction when using store's action
- use Arrow Function & Object destructuring
- use store/getters
=> docs(examples): chat example update

docs/en/api.md
=> Fix capital letter

docs/zh-cn/api.md, docs/zh-cn/getters.md
https://github.com/vuejs/vuex/compare/6e965c9...ea1e4ef
=> [docs][zh-cn] updates

docs/.vuepress/public/_redirects
=> Update _redirects for zh-cn

examples/shopping-cart/components/ProductList.vue, examples/shopping-cart/components/ShoppingCart.vue, examples/shopping-cart/store/modules/cart.js, examples/shopping-cart/store/modules/products.js
- Remove getters that return a piece of the state as is
- Make modules namespaced
- Rename cart's `added` to `items`
https://github.com/vuejs/vuex/issues/1109
=> Update shopping cart example

docs/.vuepress/public/_redirects, docs/README.md
=> docs: update outdated link and redirects

docs/zh/guide/README.md
=> fixed markdown syntax

docs/zh/README.md
=> doc: fix link in README.md

docs/zh/README.md
zh-cn document change to the right url link.
=> zh-cn document change to the right url link.

docs/ja/guide/modules.md, docs/kr/guide/modules.md, docs/ptbr/guide/modules.md, docs/zh/guide/modules.md
=> Applied #1361 to all languages

docs/guide/plugins.md
Let's update the function's name to match the code sample
=> [docs] Update plugins.md

docs/zh/api/README.md
Ref: https://github.com/vuejs/vuex/compare/f64a89c...4b82bb2
/ping @justineo
Thanks.
=> docs(zh): update

docs/zh/api/README.md
https://github.com/vuejs/vuex/compare/da22a6e...48263f8
/ping @justineo
=> docs(zh): new subscribeAction options

docs/README.md
Changes involve:
- Removal of dead links: data flow.png and vuex.png
- Removal of discourse markers (although, also, in addition) to make sentences precise
=> Fix minor errors in README.md

docs/ja/guide/hot-reload.md
コード部分が間違っているようだったので他の言語と同じくなるように修正しました。
=> docs(ja): Fix code part

docs-gitbook/pt-br/getting-started.md
Mudança de "argumetos" para "argumentos"
=> Correção de erro de digitação

docs/zh/guide/state.md
https://github.com/vuejs/vuex/compare/91f3e69...a5dd20c /ping @justineo
=> docs(zh): updated

src/store.js
=> refactor: remove useless parameter on action handlers

docs/guide/modules.md
Makes the flow of reading nicer.
=> Add missing word.

examples/shopping-cart/api/shop.js
This PR Tries to fix randomly failing e2e test.
=> ci: fix failing e2e test

test/unit/util.spec.js
spell error:
file path:  /vuex/test/unit/util.spec.js 
diff: change nornal to normal
=> modify test description

README.md
I was reading through the changes coming to v4 and noticed a minor typo.
=> Correcting typo in README

docs/zh/guide/getters.md
=> docs: update getters.md

docs/ru/guide/testing.md
Ref: https://github.com/vuejs/vuex/pull/1425
=> docs: [RU] Update testing.md

README.md
This PR revises the 4.0 branch README.
Improvements include:
- Better use of language for readability.
- Correct use of module import/export for related example code blocks.
=> chore(readme): language and example code improvements.

docs/ja/api/README.md, docs/ja/guide/hot-reload.md
This PR adds JA translation for the latest updates.
=> docs(ja): update the latest changes

docs/kr/guide/actions.md
This PR updates KR translation for actions.md in guide docs.
=> docs: Add a translation of an example in actions.md of guide docs

docs/zh/api/README.md, docs/zh/guide/hot-reload.md, docs/zh/guide/plugins.md
https://github.com/vuejs/vuex/compare/b40ee5dce715a3ba20ba5589453d0a9715825f19...7409ad489f39091e2f73a9f1b92165ae0190ca64
/cc @Justineo Thanks.
=> docs(zh): update b40ee5d...7409ad4

docs/fr/guide/plugins.md, docs/guide/plugins.md, docs/ja/guide/plugins.md, docs/kr/guide/plugins.md, docs/ptbr/guide/plugins.md, docs/ru/guide/plugins.md, docs/zh/guide/plugins.md
Inspired by https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral
=> docs: replace the use of blacklist

docs/guide/modules.md
Hey,
I found myself looking up the exact syntax repeatedly, so I'd like to contribute these examples.
Best regards,
Micha
=> docs(guide/modules): Add examples for mapGetters with namespace

package.json
fix #1787
This PR adds missing `logger.d.ts` file in the release package.
=> fix(types): add missing `logger.d.ts` file to the package (#1787)

docs/zh/guide/README.md
Sorry, I found that I added a semicolon the last time I changed the document.
=> docs(zh): Remove semicolon

docs/guide/plugins.md
=> docs: fix minor typo

docs-gitbook/pt-br/plugins.md, docs/ptbr/guide/plugins.md
Hey @kiaking 
super small fix of a broken link in the docs (found one in ptbr while searching for the broken one and fixed it too).
Cheers,
Peter
=> docs(en+ptbr): fix broken link

docs/.vitepress/config.js, docs/ptbr/api/index.md, docs/ptbr/guide/actions.md, docs/ptbr/guide/composition-api.md, docs/ptbr/guide/forms.md, docs/ptbr/guide/getters.md, docs/ptbr/guide/hot-reload.md, docs/ptbr/guide/index.md, docs/ptbr/guide/migrating-to-4-0-from-3-x.md, docs/ptbr/guide/modules.md, docs/ptbr/guide/mutations.md, docs/ptbr/guide/plugins.md, docs/ptbr/guide/state.md, docs/ptbr/guide/strict.md, docs/ptbr/guide/structure.md, docs/ptbr/guide/testing.md, docs/ptbr/guide/typescript-support.md, docs/ptbr/index.md, docs/ptbr/installation.md, docs/public/_redirects
Translated to Portuguese BR
Added config menu
@ktsn Is it already possible to make the translation available? After a review of course?
=> (Add pt-br language) Vuex 4

src/helpers.js
anthor params => another params
=> fix a little typo in the comment

package.json
=> fix: webpack bundle with 'vuex.esm-bundler.js' (#1906)

docs/guide/composition-api.md
=> spelling mistake?

docs/ptbr/guide/typescript-support.md
=> Docs (pt-br): Update typescript-support.md store.js to store.ts

docs/guide/getters.md
This is a known issue that requires Vue 3.1 to be released.  chang  to  This is a known issue that requires Vue 3.2 to be released.
=> update warning version

docs/zh/guide/getters.md
missing ':' on line 34
34 行少了一个冒号
=> missing ':' on line 34

examples/composition/shopping-cart/app.js
import { currency } from './currency'
unused
=> style: delete unused variable of shopping-cart
